services:
  - type: web
    name: dole-tupad-validator
    env: node
    buildCommand: npm run render-build
    startCommand: npm run start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max_old_space_size=4096